### PR TITLE
added github ci

### PR DESCRIPTION
**Pull request by ss89**
In this PR i added a ci, so that we can build the releases from within github actions.

It should add artifacts to releases when a tag is pushed, however that needs configuration of a github secret in the repo called `GITHUB_TOKEN` with the given permissions

Later on we could add more envs, when needed.

### CODE REVIEW

**Comment by Eisbaeeer** [comment]
@ss89 Thank you for pull-requests! The action workflow running fine. I read this article https://github.com/marketplace/actions/github-action-publish-binaries . Correct me, but there will be a small step from test compiling to publish the binary automaticaly? I never used the workflow functionality, but this is great! Perhaps you can help me to get the auto publish running?

**Comment by ss89** [comment]
I'll try to sum everything up this evening.

**Comment by ss89** [comment]
> @ss89 Thank you for pull-requests! The action workflow running fine. I read this article https://github.com/marketplace/actions/github-action-publish-binaries . Correct me, but there will be a small step from test compiling to publish the binary automaticaly? I never used the workflow functionality, but this is great! Perhaps you can help me to get the auto publish running?

The publishing step is already integrated, as you can see in the PRs comment 😃 

It will publish the assets into a (new/existing) release when you create a tag (e.g. by using the releases page and then type a new tag name).

First you'll need to obtain a personal access token by creating it here: https://github.com/settings/tokens/new with the scope repository.public_repo (because you want the token to have access to your public repositories).
Bildschirmfoto 2022-10-17 um 18 32 09

Make sure you do have an environment set-up or do that as the next step:
Bildschirmfoto 2022-10-17 um 18 33 47

Then you'll need to specify the `GITHUB_TOKEN` in the Environments page of the repositories Settings page under Secrets.
Bildschirmfoto 2022-10-17 um 18 34 51

Then you can create a Secure with name `GITHUB_TOKEN` and the value should be your personal access token from the first step:
image

After all these steps when you create a new release (i suggest a  v0.0.0-test or something) it should trigger the action just like always, but since it detects that it is running for a tag it will then also try the release action instead of skipping it. This should now theoretically work.

**Comment by Eisbaeeer** [comment]
Great. Worked like a charme! Thank you verry much!
image

**Comment by ss89** [comment]
Awesome!

**Comment by ss89** [comment]
FYI https://github.blog/2022-10-18-introducing-fine-grained-personal-access-tokens-for-github/?utm_source=tldrnewsletter

**Pull request merged**
